### ISSUE TITLE
[功能请求]让玩家查看自己的限时权限组剩余时间

### ISSUE THREAD

**Issue by ghost** [caoli5288/permission#2]
需要一个指令 来查看当前自己所在什么组,还剩多少天
虽然已经有/permission <player> 指令
但是太不亲民了... 而且可以查询他人的权限 不适合玩家使用
如果能支持的话就太感谢啦~

如果可以的话最好还能支持 [**PlaceholderAPI**](https://www.spigotmc.org/resources/placeholderapi.6245/)
这样我就可以在菜单里更直观的显示了

**Comment by caoli5288** [comment]
placeholder暂时先不管，，查询现在暂时是实时查数据库的，不建议给普通玩家用，不过我还是实现了，你自己编译最新源代码或者等我之后改进好
// 最近懒癌发作不知道啥时候有时间改

**Comment by ghost** [comment]
好的 谢谢

**Comment by caoli5288** [comment]
placeholderapi加上了，两个变量

- permission_expire_权限
  - 返回剩余时间（毫秒）
- permission_expiretime_权限
  - 返回剩余时间（直观）
