### ISSUE TITLE
[功能请求]将查询的权限和拥有的组分开

### ISSUE THREAD

**Issue by ghost** [caoli5288/permission#3]
默认是/permission 玩家名
查询玩家拥有的组和权限
能不能改成需要用两个命令来分别查询组和权限呢？
例如下面的格式
/permission group 玩家名 这个查询玩家拥有的组
/permission permission 玩家名 这个查询玩家拥有的权限

**Comment by caoli5288** [comment]
好像没有太大必要

**Comment by ghost** [comment]
唔,主要是让玩家查询界面更友好一些 并非是我自己看 我自己看当然没有太大必要啦
